version: '3.8'
services:
  stats-server:
    build: ./ewm-stat-service/stat_server
    image: ewm-stats-server
    container_name: "ewm-stats-server"
    ports:
      - "9090:9090"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  statdb:
    image: postgres:16
    volumes:
      - /var/lib/postgresql/data/
    container_name: statdb

    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  main-service:
    build: ./ewm-main-service
    image: ewm-main-service
    container_name: "ewm-main-service"
    ports:
      - "8080:8080"
    depends_on:
      - ewmdb
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  ewmdb:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewmdb
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm