create table Statistic(
    id int  generated by default as identity not null,
    app varchar(100) not null,
    uri varchar(100) not null,
    ip varchar(100) not null,
    create_time timestamp not null,
    constraint pk_stat PRIMARY KEY(id)
);