CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(254)                            not null unique,
    name  varchar(250)                            not null,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE table if not exists categories
(
    id   bigint generated by default as identity not null,
    name varchar(50)                             not null,
    constraint pk_categories primary key (id)
);

create table if not exists Locations
(
    id  bigint generated by default as identity not null,
    lat float                                   not null,
    lon float                                   not null,
    constraint pk_locations primary key (id)
);

create table if not exists Events
(
    id                 bigint generated by default as identity not null,
    annotation         varchar(2000)                           not null,
    category_id        bigint                                  not null,
    created_on         timestamp without time zone             not null,
    initiator          bigint                                  not null,
    description        varchar(7000)                           not null,
    event_date         timestamp without time zone             not null,
    location_id        bigint,
    paid               boolean                                 not null,
    participant_limit  bigint                                  not null,
    published_on       timestamp without time zone,
    request_moderation boolean                                 not null,
    state              varchar(20)                             not null,
    title              varchar(120)                            not null,
    views              bigint,
    constraint pk_events PRIMARY KEY (id),
    constraint fk_events_cat foreign key (category_id) references categories (id),
    constraint fk_events_loc foreign key (location_id) references Locations (id),
    constraint fk_events_us foreign key (initiator) references users (id)
);

create table if not exists requests
(
    id           bigint generated by default as identity not null,
    event_id     bigint                                  not null,
    requester_id bigint                                  not null,
    created      timestamp                               not null,
    status       varchar(20)                             not null,
    constraint pk_requests PRIMARY KEY (id),
    constraint fk_requests_ev foreign key (event_id) references events (id),
    constraint fk_requests_us foreign key (requester_id) references users (id)
);

create table if not exists compilations
(
    id     bigint generated by default as identity not null,
    pinned boolean                                 not null,
    title  varchar(200)                            not null,
    constraint pk_compilations primary key (id)
);

create table if not exists compilations_events
(
    compilation_id bigint not null,
    event_id       bigint not null,
    constraint fk_com_id foreign key (compilation_id) references compilations (id),
    constraint fk_ev_id foreign key (event_id) references events (id)
);

create table if not exists comments
(
    id          bigint generated by default as identity not null,
    text        varchar(500)                            not null,
    commentator bigint                                  not null,
    event       bigint                                  not null,
    created_time timestamp with time zone                not null,
    constraint fk_comm_user_id foreign key (commentator) references users (id),
    constraint fk_comm_event_id foreign key (event) references events (id)
);